[package]
name = "hdfs-jni"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[lib]
name = "hdfs"
path = "src/lib.rs"

[dependencies]
libc = "0.2"
log = "0.4"
url = "2"
thiserror = "1"

[build-dependencies]
cc = "1.0"
